eureka:
  client:
    service-url:
      defaultZone: http://test:test@localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

logging:
  file:
    name: ./logs/log-file.log

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - logfile
          - refresh

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: solicitacao-service
          uri: lb://solicitacao-service
          predicates:
            - Path=/api/v1/solicitacao/**
